### ISSUE TITLE
[BUG] Document opens in edit mode rather than auto-launching items (since 1.2)

### ISSUE THREAD

**Issue by aptonline** [gingerbeardman/stapler#25] opened 2024-08-20 16:19 UTC
**Describe the bug**
Files not opening when launching the stapler document

**To Reproduce**
Testing for the first time and adding a number of documents (.PDF,.MP4) files into a document both via drag and drop and also via 'Add files'.  Saving the document to the desktop and launching from there. The Stapler document opens and shows the added files but no documents are opening.  It appears to be opening in edit mode (command key down).

**Expected behavior**
Documents open as expected when opening the Stapler document.

**Versions (please complete the following information):**
 - Stapler version: 1.2.3
 - macOS version: 14.6.1

**Additional context**
No error messages appears and app does not crash, just shows the contents of the Stapler document.

**Comment by gingerbeardman** [comment] 2024-08-20 16:29
Please use 1.2.2 for now

**Comment by aptonline** [comment] 2024-08-20 16:35
Same issue with 1.2.2 for me.

**Comment by gingerbeardman** [comment] 2024-08-20 16:42
Keep going back until you find one that works :)

That would help me find the point at which I broke it.

Then I'll fix it later today.

**Comment by gingerbeardman** [comment] 2024-08-20 16:44
OK, I broke it in 1.2

Gah.

Will fix later on

**Comment by gingerbeardman** [comment] 2024-08-20 17:10
So, in the latest code as it stands it does still work... it's just the flaky nature of the way I am deciding if the file was opened from Finder or not to do an auto-launch is not great. See #2 

1. Open Stapler app
2. Switch to Finder
3. Double-click a Stapler Document
4. Items will auto-launch

```
if isOpenedFromFinder && !appStateManager.wasJustLaunched {
```

**Comment by gingerbeardman** [comment] 2024-08-20 21:03
Closing in favour of #2 

Feel free to reply if there's anything more to add.

**Closed by gingerbeardman** 2024-08-20 21:03 UTC
Labels: bug

**Comment by aptonline** [comment] 2024-08-21 09:26
Hi, this is still not working for me even from a cold start of the app. Same result. no documents opening.

**Comment by gingerbeardman** [comment] 2024-08-21 11:06
Screen recording please @aptonline

**Comment by aptonline** [comment] 2024-08-21 12:58
As requested, tested with no app open and then launching the document I created and testing Quick view to show the files are present.

https://github.com/user-attachments/assets/b2d84ddb-941a-4642-bd78-92b02da94ac4

**Comment by gingerbeardman** [comment] 2024-08-21 17:01
Right, I agree it's broken in this usage.

You can use my [workaround](https://github.com/gingerbeardman/stapler/issues/25#issuecomment-2299349145) (basically, leave Stapler open) until I fix this soon.

**Comment by aptonline** [comment] 2024-08-21 17:37
Leaving Stapler open and launching the document has the same result. Nothing happens.

**Comment by gingerbeardman** [comment] 2024-08-21 17:59
Well, it's leaving Stapler open in the background.

But if you're doing that, then I can't reproduce what you're seeing.

Also, what macOS version?

<img width="484" alt="Screen shot 2024-08-21 at 18 57 37" src="https://github.com/user-attachments/assets/a73faa31-b11d-4f41-8c8b-b9e54c53cbeb">

https://github.com/user-attachments/assets/e8eda74c-37df-4722-832c-ee783e0484a9

**Comment by gingerbeardman** [comment] 2024-08-21 18:20
But, this will be reworked soon so don't worry about whether or not we can agree on repro.

**Comment by aptonline** [comment] 2024-08-22 10:44
It's certainly flakey as its started working today if I leave the app open.

As an aside, would it be possible to add a preference toggle displaying the open dialog when launching the app?

**Comment by gingerbeardman** [comment] 2024-08-22 14:53
The app is not self-modifying 😆 so it can't just start working. 

Small change: https://github.com/gingerbeardman/stapler/commit/feaa002287e82e1d13f4cc4aac7ef4a35030c9c4

Will live with this for a while. Not entirely sure it's a better experience.

**Comment by aptonline** [comment] 2024-08-23 12:08
> The app is not self-modifying 😆 so it can't just start working.

And yet here we are…

I’ll test the new version when it’s released and provide an update 👍

**Comment by gingerbeardman** [comment] 2024-08-23 13:19
Had a brain wave. Cross your fingers. 

I will also put some logging in so we can check some things!

**Comment by gingerbeardman** [comment] 2024-08-23 15:47
```
// Define an enum for the different document opening scenarios
enum DocumentOpeningScenario {
	case launchedWithDocument
	case resumedBySystem
	case openedThroughFileMenu
	case openedFromFinderWhileRunning
	case unknown
}
```

**Comment by aptonline** [comment] 2024-08-23 19:05
Will give it a whirl on the next release.

**Comment by gingerbeardman** [comment] 2024-08-23 19:33
here we go https://github.com/gingerbeardman/stapler/tree/1.2.4

**Comment by aptonline** [comment] 2024-08-24 12:09
All working for me now from my tests 👍🏼
