### ISSUE TITLE
Tabbed Document Overwrites Items

### ISSUE THREAD

**Issue by maxoakland** [gingerbeardman/stapler#29] opened 2024-08-20 20:00 UTC
**Describe the bug**
I noticed you can choose "Show Tab Bar" in the View menu. I did this and clicked the plus sign to make a new document. Then I added an item to that document.

Next, I closed the tab and clicked delete. It switched back to my first document, but still showed the item I had added to the second document. I closed and reopened the document, but discovered that my original document had been completely overwritten by what I did in the tabbed document

**Expected behavior**
This shouldn't happen. At the least, disable the tab bar so a user can't run into the bug

**Screenshots**
TO BE COMPLETED

**Versions (please complete the following information):**
 - Stapler version [e.g. 1.2.3] TO BE COMPLETED
 - macOS version [e.g. 14.6.1] TO BE COMPLETED

**Additional context**

**Comment by gingerbeardman** [comment] 2024-08-20 20:58
I cannot reproduce this behaviour. Please post a screen recording or screenshot.


https://github.com/user-attachments/assets/13266d8a-5a28-4b09-a56f-f9db2c1cdd3b

**Comment by gingerbeardman** [comment] 2024-08-20 21:03
Closing.

Feel free to reply if there's anything more to add.

**Closed by gingerbeardman** 2024-08-20 21:03 UTC
Labels: bug, can't reproduce
